project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DI-CUI

format:
  html:
    theme: cosmo
    css: styles.css



